services:
  webhooks_test_app:
    image: uffizzitest/hello-world-1:latest
    environment:
      POSTGRES_USER: postgres

x-ingress:
  service: webhooks_test_app
  port: 80

x-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
